site_name: platform CLI
site_description: Primeiro Environment local com a CLI platform
site_url: https://smsilva.github.io/wasp-idp/cli/
repo_url: https://github.com/smsilva/wasp-idp
edit_uri: edit/main/cli/docs/
docs_dir: docs
nav:
  - Uso: index.md
theme:
  name: material
  language: pt-BR
  features:
    - content.code.copy
markdown_extensions:
  - admonition
  - pymdownx.superfences
