---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-alpha
  description: Example product team (owner of apps created from the python-service template)
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-beta
  description: Example product team (owner of apps created from the python-service template)
spec:
  type: team
  children: []
