# Azure providers for the cluster-zero exercise.
items:
  - name: upbound-provider-family-azure
    kind: Provider
    package: xpkg.upbound.io/upbound/provider-family-azure
    version: v2.6.2
  - name: upbound-provider-azure-authorization
    kind: Provider
    package: xpkg.upbound.io/upbound/provider-azure-authorization
    version: v2.6.2
  - name: upbound-provider-azure-containerservice
    kind: Provider
    package: xpkg.upbound.io/upbound/provider-azure-containerservice
    version: v2.6.2
  - name: upbound-provider-azure-dbforpostgresql
    kind: Provider
    package: xpkg.upbound.io/upbound/provider-azure-dbforpostgresql
    version: v2.6.2
  - name: upbound-provider-azure-eventhub
    kind: Provider
    package: xpkg.upbound.io/upbound/provider-azure-eventhub
    version: v2.6.2
  - name: upbound-provider-azure-keyvault
    kind: Provider
    package: xpkg.upbound.io/upbound/provider-azure-keyvault
    version: v2.6.2
  - name: upbound-provider-azure-managedidentity
    kind: Provider
    package: xpkg.upbound.io/upbound/provider-azure-managedidentity
    version: v2.6.2
  - name: upbound-provider-azure-management
    kind: Provider
    package: xpkg.upbound.io/upbound/provider-azure-management
    version: v2.6.2
  - name: upbound-provider-azure-network
    kind: Provider
    package: xpkg.upbound.io/upbound/provider-azure-network
    version: v2.6.2
  - name: upbound-provider-azure-storage
    kind: Provider
    package: xpkg.upbound.io/upbound/provider-azure-storage
    version: v2.6.2
