apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: foundry-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: env
                    operator: In
                    values:
                      - development
                      - production
          - git:
              repoURL: https://github.com/wasp-foundry/gitops.git
              revision: main
              directories:
                - path: apps/*
  template:
    metadata:
      name: '{{ .path.basename }}-{{ .name }}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/wasp-foundry/gitops.git
        targetRevision: main
        path: '{{ .path.path }}/overlays/{{ .name }}'
      destination:
        server: '{{ .server }}'
        namespace: '{{ .path.basename }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
