apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: foundry-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/wasp-foundry/gitops.git
        revision: main
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{ .path.basename }}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/wasp-foundry/gitops.git
        targetRevision: main
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .path.basename }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
